### ISSUE TITLE
Shape Error

### ISSUE THREAD

**Issue by zhcv** [YuvalBecker/MelNet#1]
Traceback (most recent call last):
  File "MelNet.py", line 291, in <module>
    batch_norm=1)
  File "MelNet.py", line 241, in MelNET
    Tot_matrix=tf.transpose(tf.matmul(concat_output,matwh1),[0,3,2,1])
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 2057, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4560, in mat_mul
    name=name)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 4 for 'MatMul' (op: 'MatMul') with input shapes: [?,32,50,15], [15,5].

**Comment by YuvalBecker** [comment]
Hey do you use the latest version i uploaded? and i havent uploaded requirements file, but you should use tensorflow 2 (if you dont already) . which os do you use? 
I just checked again and it runs well . so i need more information about how you run the code in order to help you .
